#!/usr/bin/env ruby -w
# frozen_string_literal: true

lib = File.expand_path("../lib", __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require "financo"

begin
  p = Financo::CLI::Program.new
  p.run

  exit(0)
rescue Financo::CLI::ParserError => e
  STDERR.puts "Error: #{e}"
  STDERR.puts "Run 'financo --help' for usage."
rescue Financo::CLI::ProgramError => e
  STDERR.puts e
end

exit(1)